name: "Amplify"
version: 1
on:
  push:
    branches:
      - main
jobs:
  backend:
    phases:
      build:
        commands:
          - amplifyPush --simple
  frontend:
    phases:
      preBuild:
        commands:
          - npm install
      build:
        commands:
          - npm run build
    artifacts:
      baseDirectory: build
      files:
        - '**/*'
    cache:
      paths:
        - node_modules/**/*
